version: "3.9"

services:
  app:
    build: .
    command: streamlit run src/app.py --server.port 8501
    ports: 
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_HEADLESS=true
      - HF_HOME=/workspace/.cache/huggingface     # keeps models on volume
    volumes:
      - .:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
